SVN_BRANCH=$(shell svn info ../../.. | grep Relative | awk '{print $$3}')
SVN_REV=$(shell svn info ../../.. | grep Revision | awk '{print $$2}')

CFLAGS += -DBOARD_NAME=HW_V03 \
	-DDEVICE_PLATFORM=DEVICE_PLATFORM_TEST \
	-D__SVN_BRANCH=\"$(SVN_BRANCH)\" \
	-D__SVN_REV=\"$(SVN_REV)\"